# Generated by Django 6.0.2 on 2026-03-04 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120, unique=True)),
                ('parts', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='customer_csvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(help_text='Part code identifier', max_length=50)),
                ('forecast', models.PositiveIntegerField(help_text='Forecasted quantity of materials')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of forecast computation')),
            ],
            options={
                'verbose_name': 'Material Forecast',
                'verbose_name_plural': 'Material Forecasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_partcode', models.CharField(max_length=80, unique=True)),
                ('mat_partname', models.CharField(max_length=160)),
                ('mat_maker', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm'), ('g', 'g'), ('kg', 'kg')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeeprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_allocations', to='app.forecastrun')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materiallist')),
            ],
            options={
                'verbose_name': 'Daily Material Allocation',
                'verbose_name_plural': 'Daily Material Allocations',
                'ordering': ['allocation_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand_qty', models.PositiveIntegerField(default=0, help_text='Physical stock counted during monthly inventory')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='app.materiallist')),
            ],
            options={
                'verbose_name': 'Material Stock',
                'verbose_name_plural': 'Material Stocks',
            },
        ),
        migrations.CreateModel(
            name='MaterialReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='app.materialstock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TEPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=60)),
                ('tep_code', models.CharField(max_length=60, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tep_codes', to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_allocated', models.PositiveIntegerField(help_text='Quantity reserved from stock')),
                ('forecast_ref', models.CharField(blank=True, help_text='Optional forecast reference (month/week/code)', max_length=50)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('fulfilled', 'Fulfilled'), ('released', 'Released')], default='reserved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_allocations', to='app.customer')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='app.materiallist')),
                ('tep_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_allocations', to='app.tepcode')),
            ],
            options={
                'verbose_name': 'Material Allocation',
                'verbose_name_plural': 'Material Allocations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_partcode', models.CharField(max_length=80)),
                ('mat_partname', models.CharField(max_length=160)),
                ('mat_maker', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm'), ('g', 'g'), ('kg', 'kg')], max_length=10)),
                ('dim_qty', models.FloatField()),
                ('loss_percent', models.FloatField(default=10.0)),
                ('total', models.FloatField()),
                ('tep_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='app.tepcode')),
            ],
        ),
        migrations.CreateModel(
            name='TEPRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('tep_code', models.CharField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('materials', models.ManyToManyField(blank=True, to='app.material')),
                ('tep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='app.tepcode')),
            ],
            options={
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='ForecastLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=120)),
                ('forecast_qty', models.PositiveIntegerField(default=0)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('tep_code', models.CharField(blank=True, default='', max_length=60)),
                ('mat_partcode', models.CharField(max_length=80)),
                ('mat_partname', models.CharField(blank=True, default='', max_length=160)),
                ('mat_maker', models.CharField(blank=True, default='', max_length=120)),
                ('unit', models.CharField(blank=True, default='', max_length=10)),
                ('per_unit_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('required_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app.forecastrun')),
            ],
            options={
                'indexes': [models.Index(fields=['part_code'], name='app_forecas_part_co_ebbfd7_idx'), models.Index(fields=['mat_partcode'], name='app_forecas_mat_par_047724_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerPartSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_month', models.DateField(help_text='Use first day of the month')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_schedules', to='app.customer')),
                ('tep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_schedules', to='app.tepcode')),
            ],
            options={
                'ordering': ['-schedule_month', 'customer__customer_name', 'tep__tep_code'],
                'unique_together': {('customer', 'tep', 'schedule_month')},
            },
        ),
    ]
