# Generated by Django 6.0.2 on 2026-03-05 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120, unique=True)),
                ('parts', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='customer_csvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_partcode', models.CharField(max_length=80, unique=True)),
                ('mat_partname', models.CharField(max_length=160)),
                ('mat_maker', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm'), ('g', 'g'), ('kg', 'kg')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeeprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand_qty', models.PositiveIntegerField(default=0, help_text='Physical stock counted during monthly inventory')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='app.materiallist')),
            ],
            options={
                'verbose_name': 'Material Stock',
                'verbose_name_plural': 'Material Stocks',
            },
        ),
        migrations.CreateModel(
            name='TEPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=60)),
                ('tep_code', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tep_codes', to='app.customer')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='app.tepcode')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_allocated', models.PositiveIntegerField(help_text='Quantity reserved from stock')),
                ('forecast_ref', models.CharField(blank=True, help_text='Optional forecast reference (month/week/code)', max_length=50)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('fulfilled', 'Fulfilled'), ('released', 'Released')], default='reserved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_allocations', to='app.customer')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='app.materiallist')),
                ('tep_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_allocations', to='app.tepcode')),
            ],
            options={
                'verbose_name': 'Material Allocation',
                'verbose_name_plural': 'Material Allocations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_partcode', models.CharField(max_length=80)),
                ('mat_partname', models.CharField(max_length=160)),
                ('mat_maker', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm'), ('g', 'g'), ('kg', 'kg')], max_length=10)),
                ('dim_qty', models.FloatField()),
                ('loss_percent', models.FloatField(default=10.0)),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tep_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='app.tepcode')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=120)),
                ('forecast_qty', models.PositiveIntegerField(default=0)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('tep_code', models.CharField(blank=True, default='', max_length=60)),
                ('mat_partcode', models.CharField(max_length=80)),
                ('mat_partname', models.CharField(blank=True, default='', max_length=160)),
                ('mat_maker', models.CharField(blank=True, default='', max_length=120)),
                ('unit', models.CharField(blank=True, default='', max_length=10)),
                ('per_unit_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('required_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app.forecastrun')),
            ],
            options={
                'indexes': [models.Index(fields=['part_code'], name='app_forecas_part_co_ebbfd7_idx'), models.Index(fields=['mat_partcode'], name='app_forecas_mat_par_047724_idx'), models.Index(fields=['run'], name='app_forecas_run_id_dc77d2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tepcode',
            index=models.Index(fields=['customer', 'part_code', 'tep_code'], name='app_tepcode_custome_f7c4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='tepcode',
            index=models.Index(fields=['is_active'], name='app_tepcode_is_acti_0fb643_idx'),
        ),
        migrations.AddIndex(
            model_name='materialallocation',
            index=models.Index(fields=['material', 'status'], name='app_materia_materia_70f922_idx'),
        ),
        migrations.AddIndex(
            model_name='materialallocation',
            index=models.Index(fields=['forecast_ref'], name='app_materia_forecas_7387cf_idx'),
        ),
        migrations.AddIndex(
            model_name='materialallocation',
            index=models.Index(fields=['customer', 'status'], name='app_materia_custome_b500d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reserved'), models.Q(('forecast_ref', ''), _negated=True)), fields=('forecast_ref', 'material', 'customer', 'tep_code'), name='uniq_reserved_per_ref_material_customer_tep'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['tep_code', 'mat_partcode'], name='app_materia_tep_cod_ff7c93_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['mat_partcode'], name='app_materia_mat_par_b419ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('tep_code', 'mat_partcode'), name='uniq_material_per_tep_partcode'),
        ),
    ]
