# Generated by Django 6.0.2 on 2026-02-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tepcode',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tepcode',
            name='tep_code',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
