# Generated by Django 6.0.2 on 2026-03-04 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTEPSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_month', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('tep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tepcode')),
            ],
            options={
                'ordering': ['-schedule_month', 'customer__customer_name', 'tep__tep_code'],
                'unique_together': {('customer', 'tep', 'schedule_month')},
            },
        ),
    ]
