# Generated by Django 6.0.2 on 2026-03-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastrun',
            name='schedule_month',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
