# Generated by Django 6.0.2 on 2026-02-25 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tepcode_unique_together_alter_tepcode_tep_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand_qty', models.PositiveIntegerField(default=0, help_text='Physical stock counted during monthly inventory')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='app.material')),
            ],
            options={
                'verbose_name': 'Material Stock',
                'verbose_name_plural': 'Material Stocks',
            },
        ),
    ]
