# Generated by Django 6.0.2 on 2026-02-25 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_materialstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstock',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='app.materiallist'),
        ),
    ]
