# Generated by Django 6.0.2 on 2026-03-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_normalize_material_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bommaterial',
            name='dim_qty',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='bommaterial',
            name='total',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='forecastline',
            name='per_unit_total',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='forecastline',
            name='required_qty',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
    ]
