# Generated by Django 6.0.2 on 2026-02-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_materialstock_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(help_text='Part code identifier', max_length=50)),
                ('forecast', models.PositiveIntegerField(help_text='Forecasted quantity of materials')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of forecast computation')),
            ],
            options={
                'verbose_name': 'Material Forecast',
                'verbose_name_plural': 'Material Forecasts',
                'ordering': ['-created_at'],
            },
        ),
    ]
