# Generated by Django 6.0.2 on 2026-02-26 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_materialstock_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_allocated', models.PositiveIntegerField(help_text='Quantity reserved from stock')),
                ('forecast_ref', models.CharField(blank=True, help_text='Optional forecast reference (month/week/code)', max_length=50)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('fulfilled', 'Fulfilled'), ('released', 'Released')], default='reserved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_allocations', to='app.customer')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='app.materiallist')),
                ('tep_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_allocations', to='app.tepcode')),
            ],
            options={
                'verbose_name': 'Material Allocation',
                'verbose_name_plural': 'Material Allocations',
                'ordering': ['created_at'],
            },
        ),
    ]
