# Generated by Django 6.0.2 on 2026-02-26 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_materialallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=120)),
                ('forecast_qty', models.PositiveIntegerField(default=0)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('tep_code', models.CharField(blank=True, default='', max_length=60)),
                ('mat_partcode', models.CharField(max_length=80)),
                ('mat_partname', models.CharField(blank=True, default='', max_length=160)),
                ('mat_maker', models.CharField(blank=True, default='', max_length=120)),
                ('unit', models.CharField(blank=True, default='', max_length=10)),
                ('per_unit_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('required_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app.forecastrun')),
            ],
            options={
                'indexes': [models.Index(fields=['part_code'], name='app_forecas_part_co_ebbfd7_idx'), models.Index(fields=['mat_partcode'], name='app_forecas_mat_par_047724_idx')],
            },
        ),
    ]
