# Generated by Django 6.0.2 on 2026-03-02 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_forecastrun_forecastline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tepcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tepcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tepcode',
            name='revised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tepcode',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='app.tepcode'),
        ),
        migrations.AddIndex(
            model_name='forecastline',
            index=models.Index(fields=['run'], name='app_forecas_run_id_dc77d2_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['tep_code', 'mat_partcode'], name='app_materia_tep_cod_ff7c93_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['mat_partcode'], name='app_materia_mat_par_b419ca_idx'),
        ),
        migrations.AddIndex(
            model_name='materialallocation',
            index=models.Index(fields=['material', 'status'], name='app_materia_materia_70f922_idx'),
        ),
        migrations.AddIndex(
            model_name='materialallocation',
            index=models.Index(fields=['forecast_ref'], name='app_materia_forecas_7387cf_idx'),
        ),
        migrations.AddIndex(
            model_name='materialallocation',
            index=models.Index(fields=['customer', 'status'], name='app_materia_custome_b500d2_idx'),
        ),
        migrations.AddIndex(
            model_name='tepcode',
            index=models.Index(fields=['customer', 'part_code', 'tep_code'], name='app_tepcode_custome_f7c4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='tepcode',
            index=models.Index(fields=['is_active'], name='app_tepcode_is_acti_0fb643_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('tep_code', 'mat_partcode'), name='uniq_material_per_tep_partcode'),
        ),
        migrations.AddConstraint(
            model_name='materialallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reserved'), models.Q(('forecast_ref', ''), _negated=True)), fields=('forecast_ref', 'material', 'customer', 'tep_code'), name='uniq_reserved_per_ref_material_customer_tep'),
        ),
    ]
