# Generated by Django 6.0.2 on 2026-02-27 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20260227_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materiallist')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_allocations', to='app.forecastrun')),
            ],
            options={
                'verbose_name': 'Daily Material Allocation',
                'verbose_name_plural': 'Daily Material Allocations',
                'ordering': ['allocation_date'],
            },
        ),
    ]
