# Generated by Django 6.0.2 on 2026-03-02 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_dailymaterialallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TEPRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('tep_code', models.CharField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('materials', models.ManyToManyField(blank=True, to='app.material')),
                ('tep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='app.tepcode')),
            ],
            options={
                'ordering': ['-revision_number'],
            },
        ),
    ]
