# Generated by Django 6.0.2 on 2026-03-03 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_teprevision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPartSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=60)),
                ('part_name', models.CharField(blank=True, default='', max_length=160)),
                ('schedule_month', models.DateField(help_text='Use first day of month')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_schedules', to='app.customer')),
            ],
            options={
                'ordering': ['-schedule_month', 'customer__customer_name', 'part_code'],
                'unique_together': {('customer', 'part_code', 'schedule_month')},
            },
        ),
    ]
