# Generated by Django 6.0.2 on 2026-03-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customerpartschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpartschedule',
            name='schedule_month',
            field=models.DateField(help_text='Use first day of the month'),
        ),
    ]
