# Generated by Django 6.0.2 on 2026-03-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_material_created_at_material_updated_at_and_more'),
        ('app', '0011_alter_customerpartschedule_schedule_month'),
    ]

    operations = [
    ]
